src/base/display.jl, src/base/iterators.jl, src/context.jl, src/dataset.jl, src/driver.jl, src/gcp.jl, src/ogr/feature.jl, src/ogr/featuredefn.jl, src/ogr/featurelayer.jl, src/ogr/fielddefn.jl, src/ogr/geometry.jl, src/ogr/styletable.jl, src/raster/colortable.jl, src/raster/rasterattributetable.jl, src/raster/rasterband.jl, src/raster/rasterio.jl, src/spatialref.jl, src/types.jl, src/utils.jl, test/REQUIRE, test/runtests.jl, test/test_dataset.jl, test/test_drivers.jl, test/test_feature.jl, test/test_gdal_tutorials.jl, test/test_geometry.jl, test/test_geos_operations.jl, test/test_ospy_examples.jl, test/test_rasterband.jl, test/test_styletable.jl
Main changes:
- introduce Wrapper Types for GDAL handles (closes #11)
- major effort at consistency in code format
- introduction of a `@gdal` macro to simplify `ccall`s
- removal of `nfeature` from `Base.display` for FeatureLayers, since it can take a prohibitively long time for some databases
- bugfixes for `simplify` and `simplifypreservetopology`
=> Provide Wrapper Types for GDAL handles

test/REQUIRE, test/test_feature.jl
it is in Base since julia v0.4, and putting it in the test/REQUIRE will cause the Dates.jl packages that is there for v0.3 compat to be downloaded
`import Dates` does nothing since Dates as a module is exported into Base
=> don't require or import Dates

.travis.yml, README.md, REQUIRE, appveyor.yml, src/base/iterators.jl, src/dataset.jl, src/driver.jl, src/gcp.jl, src/ogr/feature.jl, src/ogr/geometry.jl, src/raster/rasterattributetable.jl, src/raster/rasterband.jl, src/raster/rasterio.jl, src/types.jl, src/utils.jl, test/runtests.jl, test/test_display.jl, test/test_feature.jl, test/test_ospy_examples.jl, test/test_rasterattrtable.jl, test/test_rasterio.jl
Upgrade to 0.6
- Dropped 0.5 support
- Fixed all 0.6 deprecation warnings
- Readme now includes import Base.read
- Travis builds fixed, now with colors
- Included projection tests (was commented out)
This introduced some serious errors:
- Unescaped arguments in macros in 0.6, see JuliaLang/julia/#19587 and PR #15850
- Pointer_to_array was removed in 0.5
These are fixed now, no thanks to FactCheck (FC)
- FC complained about 8 failings tests, but not where. Compact output showed roughly where.
- The errors were actually the non existent pointer_to_array functions, which somehow didn't stop FC
- FC needs to be updated to 0.6, all remaining deprecation warnings are from FC.
Would advise to move away from FC.
=> Update to Julia 0.6, drop 0.5

REQUIRE, src/ArchGDAL.jl, src/datastreams.jl, src/ogr/feature.jl, src/ogr/geometry.jl, src/types.jl, test/test_cookbook_geometry.jl, test/test_geometry.jl, test/test_geos_operations.jl
where I stands for Interactive, since these are meant for
REPL/Interactive use, and have finalizers registered, rather than
handled through context management.
The general API is
* `unsafe_<method>(G, args…)` will return a geometry of type G
* `unsafe_<method>(args…)` will return a geometry of type Geometry (which
has to be destroyed)
* `<method>(::Function, args…)` allows for the do-block syntax which
creates a geometry::Geometry which is operated on by the function,
before being destroyed.
* `<method>(args…)` returns a geometry of type IGeometry
=> Implement Datastreams and IGeometry

test/REQUIRE, test/runtests.jl
Uses `download_verify` from BinaryProvider.
Since BinaryProvider is already needed for GDAL, I assume it's fine to depend on for the tests.
Fixes #58 
If it is downloading, it logs what it is downloading. This is probably useful to inform users why it is taking so long, or for recognizing downloading issues. Otherwise the `quiet_download` keyword could still be added.
https://github.com/JuliaPackaging/BinaryProvider.jl/blob/54b5a7822a280bbc53d803a23e6d6902fa8090ac/src/PlatformEngines.jl#L524-L526
=> add checksum to downloaded test files

appveyor.yml, test/test_cookbook_projection.jl, test/test_fielddefn.jl
as to mimic Windows user running `]test ArchGDAL`.
It seems that for Windows:
- Setting GDAL_DATA using `CPLSetConfigOption` is required
- This config is lost by calling `@testset`. You can check this by calling `AG.getconfigoption("GDAL_DATA")`.
=> Disable installing/using GDAL explicitely

src/ogr/geometry.jl
It surfaced while I was creating the example in #72
=> Support AbstractSpatialRef in all functions

Project.toml, REQUIRE
Also upped version to 0.2.1.
This will prevent breaking ArchGDAL when JuliaGEO/GDAL.jl#73 is merged.
=> Migrated to Pkg3. Pinned GDAL.

src/dataset.jl, src/utilities.jl
Removes the `failsafe` calls in dataset.jl. Don't think it is needed. If you put in a null pointer, GDAL will tell you.
And the `usage_error` should now also already be thrown by GDAL.jl.
=> aftercare, update for GDAL.jl#75

src/ArchGDAL.jl
So that `ArchGDAL.coordinates` works. Without this GeoInterface also needs to be imported to use `coordinates`, which makes a few things like using Requires.jl more complicated.
=> import GeoInterface methods explicitly

Project.toml, src/ArchGDAL.jl, src/context.jl, src/convert.jl, src/ogr/geometry.jl, src/spatialref.jl, test/runtests.jl, test/test_convert.jl, test/test_cookbook_projection.jl, test/test_geometry.jl, test/test_spatialref.jl
No tests yet, but things like `reproject` do work for any format types, which is pretty powerful allready. 
I'm not really familiar with the details of these formats or GDAL methods, so input on how to actually test these things and finish the PR will be needed. 
My intent (and knowledge) is more around generalising the structure of these package and the ecosystem so we can do all kinds of transformations without needing all the method permutations everywhere. 
For GeoData.jl this PR allows us to do `GDALarray(filepath; reproject=EPSGcode(4326))` where you can pass in anything for reproject and GeoData doesn't need to know what it is, but your lat/lon coords will just work.
The type wrappers are coming from https://github.com/rafaqz/GeoFormatTypes.jl
=> WIP: Geo format type wrappers and generic methods

src/convert.jl, src/ogr/geometry.jl, src/spatialref.jl, test/test_cookbook_projection.jl, test/test_spatialref.jl
This is a first pass at setting `OSRAxisMappingStrategy` with a keyword argument.
I'm not sure how to implement it for `fromWKT` etc methods, where the `@gdal` macro is used, so some input on that would be helpful.
But otherwise it works for reprojecting points.
The default is `:trad` now for testing, but we can change that to `:compliant` depending on what people want the default behaviour to be for ArchGDAL
closes #119
=> Add a kwarg to set OSRAxisMappingStrategy

.travis.yml, Project.toml, appveyor.yml, test/test_cookbook_projection.jl
To always make use of the new GDAL build system (jll). Should make support easier but bumps our Julia version from LTS to 1.3.
=> require julia 1.3 / GDAL build with artifacts

src/raster/rasterio.jl, test/test_rasterio.jl
The user now has more freedom of entering the bands he wishes to load, no conversion to Int32 is needed anymore. This all works now:
```julia
ds = ag.read("somefile")
img = ag.read(ds, 1)
img = ag.read(ds, [1,2,3,4])
img = ag.read(ds, Int8[1,2,3,4])
img = ag.read(ds, (1,2,3,4))
```
Fixes #126
=> Remove type specification from indices argument in rasterio.jl

test/REQUIRE
This file shouldn't be used by the package manager anymore and can be deleted. The test dependencies are set in the Project.toml file under extras.
=> Delete Require file in test folder

.travis.yml, Project.toml, docs/Project.toml, test/remotefiles.jl, test/runtests.jl
it is a deprecated alias for `jobs` (see https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Travis-CI for details)
Ref. #134. (I don't know if it fixes it yet)
I have generated a new SSH Deploy Key called "Documenter.jl Deploy Key" and followed https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#travis-ssh to add an env variable called `DOCUMENTER_KEY` to Travis CI. I'll remove the old SSH Deploy Key called "documenter" once we manage to get things up and running with the new key.
=> Remove the matrix for Travis CI

docs/make.jl, docs/src/quickstart.md
Addressing the discussion at #40, this PR is an attempt to add a tutorial in the documentation, similar to [Rasterio's Python Quickstart](https://rasterio.readthedocs.io/en/latest/quickstart.html).
=> Introductory tutorial similar to Rasterio's Python Quickstart

Project.toml, src/raster/rasterio.jl, test/test_rasterio.jl
Fixes #132
Fixes #78, with the possible exception noted in https://github.com/yeesian/ArchGDAL.jl/issues/78#issuecomment-496205117:
> We'll have to be careful about how rasterio is invoked (for [linespace and bandspace](https://github.com/yeesian/ArchGDAL.jl/blob/9cc11c3f3caa57b57680725a356b24db8ff069c8/src/raster/rasterio.jl#L2-L55)) too
I'm not really sure how those `linespace` and `bandspace` work. Should `width(dataset), height(dataset)` be replaced by looking at the buffer sizes in that method? If not clear, let's just merge this and park this as an issue to look into later.
=> fix too large buffer sizes on reduced reads

.travis.yml
This should allow failures to happen on julia nightly. 
I think this is the only reason, why the docs haven't been built for the releases 0.5.1 and 0.5.2.
Should be the next step to close #134
=> Allow test failures on julia nightly

Project.toml, src/base/display.jl, test/test_display.jl
Getting the WKT of a (complex) geometry is non trivial and will slow down things especially when used in Tables.
With this PR:
When used in a Table (compact)
```julia
julia> df = DataFrame(geom=createpoint.(coords), name="test")
10×2 DataFrame
Row │ geom                name
│ IGeometr…           String
─────┼────────────────────────────
1 │ Geometry: wkbPoint  test
2 │ Geometry: wkbPoint  test
3 │ Geometry: wkbPoint  test
4 │ Geometry: wkbPoint  test
5 │ Geometry: wkbPoint  test
6 │ Geometry: wkbPoint  test
7 │ Geometry: wkbPoint  test
8 │ Geometry: wkbPoint  test
9 │ Geometry: wkbPoint  test
10 │ Geometry: wkbPoint  test
```
Individual or array (non-compact) usage
```julia
julia> df[1, :geom]
Geometry: POINT (0.394776848700807 0.244117475869569)
```
=> Compact display of geometry without WKT

src/driver.jl, src/utils.jl, test/runtests.jl, test/test_drivers.jl, test/test_utils.jl
I'm not sure if these methods are the _best_ way to organise this kind of functionality, or the best names. But it's useful for writing arbitrary drivers without specifying them.
Closes #173
=> add methods to get driver shortname from filename extension

Project.toml, src/raster/rasterband.jl, test/test_display.jl, test/test_ospy_examples.jl, test/test_rasterband.jl
Currently the `getnodatavalue` always returns a value for a `RasterBand`, no matter if one is actually defined or not. After applying this change, `nothing` would be returned instead if there is no such value defined. I think although this would be breaking, it would enable a more fine-grained control for handling data with unknown content. 
As an alternative and to not break existing code, one could add a `hasnodatavalue` function instead. I would like to hear other opinions, maybe @rafaqz or @evetion could give a hint how it would affect GeoData.jl and GeoArrays.jl?
I would still need to fix the unit tests but wanted to hear some general opinions first.
=> Let getnodatavalue return nothing if there is none

Project.toml
There are still packages with older dependencies, and these should work equally well here?
=> looser ImageCore and ColorTypes deps

src/types.jl, test/test_rasterio.jl, test/test_types.jl
This adds GDT_CFloat* to the supported types in the conversion and allows to load complex raster data. 
I am not sure, whether the test case in tests_rasterio.jl is at the correct place, but I wanted to test whether the reading and writing of complex data works because the test in test_types.jl also works currently without conversion.
This would partially close #170.
=> Add support for complex gdal data type

.github/workflows/TagBot.yml
This should enable TagBot to also trigger documentation builds for the tagged versions.
This fix the problems of the generation of stable docs as noticed in #210.
I assume, that the DOCUMENTER_KEY is already generated, because the development version of the docs are working fine.
See https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#GitHub-Actions
=> Add DOCUMENTER_KEY as ssh deploy key to tagbot

src/ogr/featurelayer.jl, src/types.jl
Fixes #212.
I'll think about a more systematic way of catching such classes of bugs in #171, but just wanted to address the reported bug first.
=> Bugfix for dataset ownership when creating layers

src/ogr/feature.jl, src/types.jl, test/test_convert.jl, test/test_feature.jl
In order to write slightly more exotic types as `Int16`, `Bool` and `Float32`, GDAL has subtypes. However, the main type must still be set and currently ArchGDAL doesn't support these types.
I pirated it myself in https://github.com/evetion/GeoDataFrames.jl/blob/master/src/io.jl#L14, this is the upstream fix.
For the actual usage of these subtypes (in writing) see https://github.com/evetion/GeoDataFrames.jl/blob/master/src/io.jl#L103. Note that funnily enough, this enables write support of these types earlier than read support (#177).
=> Add possible subtypes

src/ArchGDAL.jl, src/types.jl, src/utils.jl, test/test_types.jl
Fixes #235
I have handled the bidirectional conversion between `ArchGDAL.GDALDataType` and `ImageCore.Normed` via `UnionAll` case in `@convert` macro
It gives: 
```julia 
julia> using ArchGDAL
julia> using ImageCore
julia> convert(ArchGDAL.GDALDataType, N0f8)
GDT_Byte::GDALDataType = 1
julia> convert(Normed, ArchGDAL.GDT_Byte)
N0f8 (alias for Normed{UInt8, 8})
```
=> Bidirectional conversion between `GDALDataType` and `ImageCore.Normed` via `UnionAll` case in `@convert` macro

src/dataset.jl, test/test_dataset.jl
Fixes #190.
~~@visr There's a small drop in test coverage due to the drop in test coverage for [`cplerr`](https://github.com/yeesian/ArchGDAL.jl/blob/f98a7cdce3482691ab526e3fbbf796d23aec35ed/src/utils.jl#L137-L143). However, I haven't been able to come up with a scenario in which I'll actually get `CE_Failure` without GDAL.jl throwing an `GDAL.GDALError`. (Which I think is a good thing!)~~ (Update: fixed by Felix in https://github.com/yeesian/ArchGDAL.jl/pull/236#discussion_r698527429)
=> Return the default geotransform rather than throwing an error.

Project.toml, src/ArchGDAL.jl, src/utils.jl, test/test_types.jl
Fixes #232
Assert "default type comes last" for mappings that are not bijective
I have enriched the `@convert` macro's docstring with some explanations and added a note on "default type comes last"
---
Before going further, @yeesian could you elaborate on:
>  asserting "default type comes last" for mappings that are not bijective.
Should we enforce it with something like:
1) enhance the readability of the macro call
```julia
@convert(
OGRFieldType::DataType,
OFTInteger::(Bool, Int16, Int32, ) # default type comes last
OFTInteger64::Int64,
)
```
and assert that all type ids of type 1 and all type ids / subtypes of type 2 are unique?
2) Or is it enough to assert that all type id <-> type id / subtype mappings are unique in `args`? 
3) Or something else?
=> Handle non-bijective data-type conversions more robustly

.github/workflows/CI.yml, .gitignore, docs/Project.toml, docs/src/projections.md
- Fixed a dead link to GDAL tutorial on CRS and transformations in docs/src/projections.md
- Added a subset of Python GDAL/OGR Cookbook, to illustrate reprojecting on features obtained from a read dataset/layer
@visr and @yeesian: is there a way to embed a preview on documentation modifications in Github comments ?
=> Fixes a dead link in docs/src/projections.md + an additional example on reprojecting

.gitignore, src/dataset.jl, test/test_dataset.jl
Fixes #256
Added:
- a new method to `AG.getlayer` without index or name arg
it raises a warning when called on a dataset with more than one layer 
- a test on the above warning
Cleaned some remaining mentions of Table in `getlayer` methods
```julia
julia> AG.read("test/data/point.geojson") do ds
layer = AG.getlayer(ds)
println(layer)
new_ds = AG.copy(layer; name="duplicated layer 1").ownedby
AG.copy(layer; dataset = new_ds, name="duplicated layer 2")
println("Number of layers: $(AG.nlayer(new_ds))")
println(AG.getlayer(new_ds))
end
Layer: point
Geometry 0 (): [wkbPoint], POINT (100 0), POINT (100.2785 0.0893), ...
Field 0 (FID): [OFTReal], 2.0, 3.0, 0.0, 3.0
Field 1 (pointname): [OFTString], point-a, point-b, a, b
Number of layers: 2
┌ Warning: Dataset has multiple layers, getting the …
```
=> Added a new method to `AG.getlayer` without index or name arg

src/utils.jl, test/test_utils.jl
The @ogrerr macro just printed whatever was passed to it in the source, which was often unhelpful (for instance, in `setfeature!`, "Failed to set feature." This change prints a human-readable message based on the OGR error code, in addition to the message passed to ogrerr.
=> add detailed error messages to @ogrerr

src/raster/array.jl, src/raster/images.jl, test/test_images.jl
The single argument normedview is only for UInt8.
This assumes that the full range will be used to go from 0 to 1.
https://juliaimages.org/stable/function_reference/#ImageCore.normedview
I ran into this with a UInt16 landsat image, and with this change I can `imread` it. Though I see that the tests only cover UInt8.
EDIT: added a second commit to make imread work on RasterDataset
=> support imview for Unsigned besides UInt8

Project.toml
I just removed the DiskArrays 0.2.4 compat entry in the Project toml, because ArchGDAL is not compatible with the old version. You would have to tag a new version and remove the broken one from the registry. Closes https://github.com/rafaqz/Rasters.jl/issues/244 and https://github.com/yeesian/ArchGDAL.jl/issues/277
=> remove DiskArrays 0.2.4 compat

src/ogr/geometry.jl
Two places in the docstrings refer to getNumPoints() and getNumGeometries(), which are GDAL functions not directly wrapped in ArchGDAL. Instead, refer to ngeom which is the ArchGDAL equivalent of both. No code changes.
=> replace references to getNumPoint() and getNumGeometries() with ngeom

docs/src/geometries.md, src/ogr/geometry.jl, src/types.jl, test/runtests.jl, test/test_prepared_geometry.jl
Preparing geometry is useful when you repeat spatial operations on a geometry, as required, calculated, information needed for said operation is cached. See https://blog.cleverelephant.ca/2008/10/postgis-performance-prepared-geometry.html
The open question is if/where we check for the remaining GDAL `ogrhaspreparedgeometrysupport` method in all these calls. Maybe a warning on init? I'm not sure what happens when a non-Yggdrasil GDAL doesn't have prepgeom support.
=> Enable preperation of geometry

Project.toml, src/ogr/feature.jl, src/types.jl, test/test_convert.jl, test/test_feature.jl
As an extension of #220. I've taken some of the work of @mathieu17g from the WIP at #243 in terms of type conversions.
Adds support for reading again (which broke somewhere during the 0.8 release train)
- OFSTBoolean
- OFSTInt16
- OFSTFloat32
Make sure we can write
- Int8
- UInt8
- UInt16
- UInt32
- Float16
By widening the type (i.e. `UInt32` => `Int64`), which requires the correct conversion in both `OGRFieldType` as `OGRFieldSubType`.
=> Enable more exotic types in reading and writing.

Project.toml, src/base/display.jl, src/base/iterators.jl, src/ogr/feature.jl, src/ogr/featuredefn.jl, src/ogr/featurelayer.jl, src/ogr/fielddefn.jl, src/tables.jl, src/types.jl
Triggered by out of memory errors when working with a *lot* of GeoDataFrames.
It seems that `iterate` just allocates `Feature`s without anyone ever cleaning them. This PR introduces an `IFeature` (and its parent `AbstractFeature`), which should align nicely with the other types.
Since GeoDataFrames goes through quite some calls, it is a bit hard to find these things, but I expect this is not the only memory leak remaining.
=> Added IFeature type. Fixed memory leakage for `Feature`s.

Project.toml, src/geointerface.jl, test/test_geos_operations.jl
Before we always returned the 3d extent, even on 2d geometries.
=> Return extent based on dimensionality.

src/ogr/feature.jl, src/types.jl, test/test_feature.jl, test/test_types.jl
As a table with an Vector{<:Enum} now can't be written. Enum stores the flags as Integer, so we already have the means to write its values. The only drawback is that we cannot restore the Enum once the value has been written.
=> Add conversion for Enum types.

Project.toml
Reverts yeesian/ArchGDAL.jl#328.
I realize I forgot to release the previous minor version (i.e. `v0.9.2`); so revert to it. See https://github.com/JuliaRegistries/General/pull/69387#issuecomment-1264730866
=> Revert "Create a new minor release"

src/geointerface.jl, src/ogr/geometry.jl, src/types.jl, test/test_geometry.jl, test/test_prepared_geometry.jl
Improves type stability where possible by keeping enums as types in `Val{wkbLineString}` and by forcing child object types from `getgeom`.
~~Also adds a low allocation `getpoint` method.~~
Edit: review when I get tests passing, can't always test on a local machine at present
=> performance and type stability fixes for geometries

src/ogr/feature.jl, test/test_feature.jl
=> Add support for OFSTJSON when fetching fields

docs/src/memory.md, src/base/iterators.jl, src/dataset.jl, src/driver.jl, src/ogr/feature.jl, src/ogr/featuredefn.jl, src/ogr/featurelayer.jl, src/ogr/fielddefn.jl, src/ogr/geometry.jl, src/ogr/styletable.jl, src/raster/colortable.jl, src/raster/images.jl, src/raster/rasterattributetable.jl, src/raster/rasterband.jl, src/raster/rasterio.jl, src/spatialref.jl, src/types.jl, src/utilities.jl, src/utils.jl, test/test_geometry.jl, test/test_rasterband.jl, test/test_types.jl
Adress #347, alternative approach to #348, based on discussion in #347.
Still has a few errors, like this:
```
Expression: AG.toWKT(AG.createlinearring([1, 2, 3], [4, 5, 6])) == AG.toWKT(AG.createlinearring([1.0, 2.0, 3.0], [4.0, 5.0, 6.0])) == "LINEARRING (1 4,2 5,3 6)"
MethodError: no method matching ArchGDAL.IGeometry{ArchGDAL.wkbLineString}(::ArchGDAL.Geometry{ArchGDAL.wkbLineString})
Closest candidates are:
ArchGDAL.IGeometry{T}(::Ptr{Nothing}) where T
@ ArchGDAL D:\visser_mn\.julia\dev\ArchGDAL\src\types.jl:251
Stacktrace:
[1] createlinearring(xs::Vector{Int64}, ys::Vector{Int64})
@ ArchGDAL D:\visser_mn\.julia\dev\ArchGDAL\src\ogr\geometry.jl:1751
[2] macro expansion
@ D:\visser_mn\.julia\juliaup\julia-1.10.0-latest+0.x64\share\julia\stdlib\v1.10\Test\src\Test.jl:477 [inlined]
[3] …
```
=> let ccall get the pointers using unsafe_convert

src/utils.jl
We never created the cfunction correctly in the macro, but because it became C_NULL, this was never noticed. (Also it seems no-one uses progress callbacks.). 
Oddly enough, on 1.8.2 the undefined behaviour changed, which started crashing M1 macs.
Probably fixes https://github.com/JuliaLang/julia/issues/47193.
=> Fix macro callback.

CHANGELOG.md, src/geointerface.jl, test/test_geometry.jl
This is a breaking change.
For background see https://github.com/JuliaGeo/GeoInterface.jl/pull/66. Brought up in https://github.com/yeesian/ArchGDAL.jl/issues/189#issuecomment-1368537576.
Soon https://github.com/JuliaGeo/GeoInterface.jl/pull/85 will provide extra options for conversion, though this doesn't help ArchGDAL as much, since you always convert to `IGeometry` anyway. And it is not breaking so no need to wait for that.
After this is in, shall we tag v0.10?
=> [breaking] switch from Base.convert to GeoInterface.convert

src/geointerface.jl, test/test_geometry.jl
This allows us to do `GeoInterface.convert(ArchGDAL, geom)` with any GeoInterface.jl compatible geometry.
=> implement module convert for geometries

src/context.jl, src/spatialref.jl, test/test_spatialref.jl
Now we can do:
```julia
julia> p = ArchGDAL.importUSER("EPSG:4326+3855")
Spatial Reference System: +proj=longlat +datum=WGS84 +geoidgr ... _defs
```
Note how there's now `+geoidgrid` present, which represents the vertical transform of EPSG:3855.
=> Introduce `importUSER` for setting SRS from custom strings.

src/geointerface.jl, test/test_geometry.jl
`getpoint` is pretty slow currently, to the point rasterizing a shapefile from ArchGDAL.jl is 20x slower than one from Shapefile.jl. Mostly because getting points allocates every time.
This PR greatly (but not completely) reduces the gap by:
1. Not returning GDAL points. They are pretty inefficient when we have thousands of points. A `Tuple` is better.
2. Preallocating `Ref` for `getpoint!` in the iterator for `Geointerfce.getpoint(linestring)`, and reusing them for each point. 
This is implemented for line string but that means polygon will also work. It's probably not worth the effort of passing the Ref through from polygons, but I haven't checked. There may be more objects that need this treatment.
Edit: I assumed this would have a test already, but seems not.
=> faster getpoint

src/geointerface.jl, test/test_geometry.jl
Throw an error on wrong index to `getcoord` instead of returning `nothing`. This was pretty bad for inference and ran into bugs in base and other poorly inferenced functions in Meshes.jl to cause hangs.
@ErickChacon this should fix the other half of your inference bug. Thanks for persevering to find problems in both packages and Base!
=> fix inference on GI.getcoord

src/dataset.jl, test/test_dataset.jl
Hi! I have factored out the layer copying from writelayers into its own function. So basically I changed (pseudocode):
```julia
function writelayers()
create() do
copystuff
end
end
```
to 
```julia
function writelayers()
create() do
copylayers(src, dst)
end
end
function copylayers(src, dst, ...)
copystuff
end
```
That should now allow to copy data from and to arbitrary datasets, whether on disk or not. You can also give the layer indices you want to be copied. I added a tiny test for that. Furthermore I adjusted the docstrings for nicer rendering in the REPL. I'm not sure with the naming `copylayers`, is it ok? What do you think in general? Lastly, this supersedes https://github.com/yeesian/ArchGDAL.jl/pull/381, but I can take that part out if you want to merge this before the change to …
=> factor out layer copying into its own function

test/test_feature.jl, test/test_tables.jl
This fixes issues with [GDAL 3.7.2](https://github.com/OSGeo/gdal/blob/v3.7.2/NEWS.md). Nothing major, see individual commit messages for details. This will only pass after https://github.com/JuliaGeo/GDAL.jl/pull/161 is merged.
=> fix tests with GDAL 3.7.2

Project.toml, src/convert.jl, src/geointerface.jl, test/test_cookbook_projection.jl, test/test_rasterband.jl, test/test_rasterio.jl, test/test_spatialref.jl
As found here https://discourse.julialang.org/t/retrieving-crs-from-vector-and-raster-data/107903/4
One can now do `GeoInterface.crs` on a geometry, layer and dataset.
Also implements a convert method to GFT from an AbstractSpatialRef.
=> Implement GeoInterface.crs

src/raster/rasterio.jl, test/test_rasterio.jl
This widens the dispatch of the `read!` and `rasterio!` functions so that the buffer can be an AbstractArray instead of a normal Array. This will allow to also read into for example views or other array wrapper types like PermuteDimsArrays. 
This would close #410. 
It will also close https://github.com/rafaqz/Rasters.jl/issues/596
Should we also widen the buffer type for the write! functions?
=> Make buffer for `read!` an AbstractArray

src/raster/array.jl, test/test_array.jl
This allows to use AG.gdalinfo on  a RasterDataset.
=> Forward gdalinfo for RasterDataset

test/test_drivers.jl, test/test_feature.jl, test/test_gdalutilities_errors.jl
Fixes #444
Changes
- FastGetExtent is now supported
- GDAL now [seals layer definitions](https://gdal.org/en/latest/development/rfc/rfc97_feature_and_fielddefn_sealing.html), which we cannot undo via C, making this test mostly moot.
- unsafe_gdaldem crashes the Julia process because of invalid arguments
The latter two require further changes, but it would be good to have the CI green for other PRs first.
=> Fix tests for GDAL 3.9.

src/ogr/feature.jl
Fixes https://github.com/evetion/GeoDataFrames.jl/issues/86
This PR adds a `copy` around `unsafe_wrap` when getting vectors out of GDAL features.  This guards against GDAL overwriting that memory, as we found in the issue.
Not sure how best to test that this works.  A memory sweat test might crash the CI....
=> `copy` all array like feature fields after `unsafe_wrap`

.github/workflows/CI.yml, .github/workflows/CompatHelper.yml, Project.toml, README.md
As 1.10 is the new LTS, and 1.6 gives failures.
=> Drop support for Julia 1.6.

src/spatialref.jl, test/test_spatialref.jl
Encountered in https://github.com/evetion/GeoDataFrames.jl/pull/92, where I try to write native GeoParquet files with ArchGDAL.
=> Add support for GFT.ProjJSON.
