yeesian/ArchGDAL.jl

- src/ArchGDAL.jl
- src/base/display.jl
- src/base/iterators.jl
- src/context.jl
- src/dataset.jl
- src/driver.jl
- src/gcp.jl
- src/metadata.jl
- src/ogr/featuredefn.jl
- src/ogr/featurelayer.jl
- src/ogr/fielddefn.jl
- src/ogr/geometry.jl
- src/raster/rasterband.jl
- src/raster/rasterio.jl
- src/spatialref.jl
- src/types.jl
- src/utils.jl
- test/test_cookbook_geometry.jl
- test/test_gdal_tutorials.jl
- test/test_ospy_examples.jl
- switch to enums
- remove borrow_
- escape quotes in docstrings
- add extraargs to rasterio
- update tests
> Massive change

- REQUIRE
- appveyor.yml
- src/base/display.jl
- src/context.jl
- src/ogr/feature.jl
- src/ogr/geometry.jl
- src/spatialref.jl
- src/types.jl
- test/runtests.jl
- test/test_cookbook_geometry.jl
- test/test_cookbook_projection.jl
- test/test_gdal_tutorials.jl
- test/test_geos_operations.jl
to support multiple types of wrappers for GDALGeometries, e.g. some that might have a finalizer, others that don't.
> Introduce AbstractGeometry

- test/REQUIRE
- test/runtests.jl
- test/test_cookbook_geometry.jl
- test/test_cookbook_projection.jl
- test/test_dataset.jl
- test/test_display.jl
- test/test_drivers.jl
- test/test_feature.jl
- test/test_featurelayer.jl
- test/test_fielddefn.jl
- test/test_gdal_tutorials.jl
- test/test_geometry.jl
- test/test_geos_operations.jl
- test/test_ospy_examples.jl
- test/test_rasterattrtable.jl
- test/test_rasterband.jl
- test/test_rasterio.jl
- test/test_styletable.jl
- test/test_types.jl
> Migrated to Base.Test

- .travis.yml
- src/base/display.jl
- src/ogr/geometry.jl
- src/raster/rasterio.jl
- src/types.jl
- test/test_cookbook_geometry.jl
- test/test_feature.jl
- test/test_fielddefn.jl
- test/test_gdal_tutorials.jl
- test/test_geometry.jl
- test/test_ospy_examples.jl
- test/test_rasterattrtable.jl
- test/test_rasterband.jl
- test/test_styletable.jl
- test/test_types.jl
Ref https://github.com/visr/GDAL.jl/pull/41
> Update for latest Julia/GDAL/Clang.jl

- .travis.yml
Circumvents visr/GDAL.jl#42
See also visr/GDAL.jl#45
> Fix travis build by circumventing GDAL problem

- test/runtests.jl
Original version didn't work on Windows.
> Changed Linux `rm` to Julia `rm()`

- docs/src/rasters.md
> Update documentation on order of dimensions.

- Project.toml
*Don't laugh, I thought I was typing the commit message when I was in fact typing the branch name.*
Ok to merge then make a new patch release?
Ref https://github.com/yeesian/ArchGDAL.jl/commit/c4258068de655d0642ecd95593593f6ecd3b6b60#commitcomment-36176047
> bump patch version and add compat entries

- src/ArchGDAL.jl
- src/raster/array.jl
- test/runtests.jl
- test/test_array.jl
Tests aren't included yet, but this works great.
I'm not sure how much to support, but we could also define `setindex!` that calls `write`
> Array interface

- test/remotefiles.jl
for some reason this function is no longer exported from Pkg.PlatformEngines
> fix downloading test data on julia nightly

- docs/Project.toml
mainly to get that CI button green again with the new GDAL and PROJ builds
> build docs on latest Documenter

- test/test_fielddefn.jl
- test/test_gdal_tutorials.jl
- test/test_gdalutilities.jl
- test/test_geos_operations.jl
- test/test_spatialref.jl
- test/test_types.jl
Most were disabled due to resolved issues with the build
> enable some tests

- Project.toml
> ArchGDAL v0.7.0 release

- .github/workflows/DocCleanup.yml
By following https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#gh-pages-Branch.
> Workflow for cleaning up preview and history.

- test/test_array.jl
In preparation for https://github.com/JuliaLang/julia/pull/41885
> Generalize exception type

- test/test_rasterband.jl
Partial fix for #285. Required due to change in https://github.com/JuliaLang/julia/pull/44096
> Fix nightly by setting the type of Vector to prevent unwanted promotion

- Project.toml
- src/utils.jl
> Workaround for unsupported function closures on :aarch64 platforms.

- src/base/display.jl
- test/test_display.jl
> Don't print WKT of prepared geometries.

- Project.toml
I'm assuming that #316 doesn't require a new major release; please let me know if I missed anything
> Create new minor release

- .github/workflows/CompatHelper.yml
https://juliaregistries.github.io/CompatHelper.jl/dev/#Creating-SSH-Key
> make CompatHelper trigger tests

- src/geointerface.jl
- test/test_feature.jl
From @felixcremer's slack thread on GeometryOps reproject + https://github.com/rafaqz/Rasters.jl/pull/853
> Define FeatureTrait for AbstractFeature

- Project.toml
- src/driver.jl
- test/test_dataset.jl
- test/test_drivers.jl
- test/test_ospy_examples.jl
Mainly wanted to check if there is anything to worry about in the failing integration tests in https://github.com/JuliaGeo/GDAL.jl/pull/194. It doesn't seem like it. This will fail until that PR is released.
> Fix tests for GDAL 3.11
